name: tachometer

on:
  push:
  workflow_dispatch:
    # allows triggering from the github UI

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Setup repo to run benchmarks
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21

        env:
          # Force installed chromedriver version to match the available chrome
          # version regardless of package-lock
          # https://github.com/giggio/node-chromedriver?tab=readme-ov-file#detect-chromedriver-version
          DETECT_CHROMEDRIVER_VERSION: true
      - run: npm i
      - run: npm i --devDependencies
      - run: npm run build

      # Run benchmarks
      - name: Run tachometer and generate results file
        run: npm run benchmarks

      # Read results and post comment
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@v2
        with:
          path: results.json
